# ==================== Import Packages ==================== #
import time
import sys
import os 

import numpy as np 
import json 


import re 

import traceback

# ==================== Constant Parameters ==================== #


prompt_specific_question_w_example = '''System Prompt: 
You are an expert AI assistant specializing in Image Editing Quality Assurance (QA). Your primary role is to act as a meticulous verifier of digital image edits.
Your task is to analyze an Original Image and a corresponding Edit Instruction, and then generate a set of exactly 5 specific, verifiable questions. The fundamental rule is this: if a human reviewer answers "yes" to all 5 of your questions, it must unequivocally confirm that the edit was successfully and perfectly executed according to the instruction.

Core Principles for Question Generation:

Instruction-Centric: Every question must directly derive from the Edit Instruction. Deconstruct the instruction into its core components (e.g., object, action, style, location).
Binary & Objective: Frame each question to be answerable with a simple and objective "Yes" or "No". Avoid subjective questions like "Does it look better?" and instead focus on verifiable facts, such as "Has the color of the car been changed from blue to red?".
Comprehensive Coverage: Your 5 questions must collectively cover all aspects of the instruction. If the instruction is "Make the man taller and add a hat," you must have questions that verify both his height and the presence of the hat.
Negative Verification (No Collateral Damage): At least one question must check for unintended side effects. This includes verifying that parts of the image not mentioned in the instruction remain unchanged, and that no new artifacts, blurs, or distortions have been introduced.
Holistic Quality Check: At least one question must assess the overall integration and realism of the edit. It should check if the edit blends seamlessly with the rest of the image, maintaining consistent lighting, shadows, and texture.

Input Format:
- Original Image: [The initial image before editing]
- Edit Instruction: [A text description of the desired change]

Output Format:
- every question MUST be phrased so that a "yes" answer confirms a positive outcome.
- Return a single JSON object with the following structure:
{
"questions": [
"Question 1",
"Question 2",
"Question 3",
"Question 4",
"Question 5"
]
}

Example Walkthrough:
INPUT:

Original Image: A photo of a golden retriever in a park.
Edit Instruction: "Add a small, green wizard hat on the dog's head."
EXPECTED OUTPUT (Generated by you):

{
"questions": [
"Is there a hat present on the dog's head that was not in the original image?",
"Is the color of the added hat predominantly green?",
"Does the shape of the hat resemble a pointed wizard hat?",
"Does the added hat appear proportional and correctly placed on the dog's head without looking unnatural?",
"Has the rest of the image, including the dog's body and the park background, remained unchanged?"
]
}

User:
Edit Instruction: <edit_instruction>'''



# ==================== Functions ==================== #

def process_single_item_generate_specific_question(image_prompts, instruction, model, max_retries=15, **kwargs):

    for retry in range(max_retries):
        try:
            text_prompt = prompt_specific_question_w_example.replace("<edit_instruction>", instruction) 
            prompt = model.prepare_prompt(image_prompts, text_prompt)
            response = model.get_parsed_output(prompt)

            match = re.search(r'{[\s\S]*}', response)
            if match:
                response_clean = match.group(0)
                data = json.loads(response_clean)
            else:
                print(response)
                raise ValueError("No JSON found in response")

            output_dict = {}

            output_dict["questions"] = data["questions"]
            for temp_key in kwargs:
                output_dict[temp_key] = kwargs[temp_key]

            return output_dict
        
        except Exception as e:
            print("Error occurred:")
            traceback.print_exc()

            if retry < max_retries - 1:
                wait_time = (retry + 1) * 2  # exponential-ish backoff: 2s, 4s, 6s...
                print(f"Error processing (attempt {retry + 1}/{max_retries}): {e}")
                print(f"Waiting {wait_time} seconds before retry...")
                time.sleep(wait_time)
            else:
                print(f"Failed to process after {max_retries} attempts: {e}")
                return

    return None 








